id: P006926
initial_creation_type: ocr
source_metadata:
  id: bdr:W24686
  title: སྒྲུབ་བརྒྱུད་ཀརྨ་ཀཾ་ཚང་གི་བརྒྱུད་པ་རིན་པོ་ཆེའི་རྣམ་པར་ཐར་པ་རབ་འབྱམས་ནོར་བུ་ཟླ་བ་ཆུ་ཤེལ་གྱི་ཕྲེང་བ
  author: ''
  volumes:
    57a804ceab2d450abec701f822361478:
      image_group_id: I1GS105611
      title: ''
      volume_number: 1
      total_pages: 958
