id: opecha:P006926
initial_creation_type: ocr
source_metadata:
  id: bdr:W24686
  title: སྒྲུབ་བརྒྱུད་ཀརྨ་ཀཾ་ཚང་གི་བརྒྱུད་པ་རིན་པོ་ཆེའི་རྣམ་པར་ཐར་པ་རབ་འབྱམས་ནོར་བུ་ཟླ་བ་ཆུ་ཤེལ་གྱི་ཕྲེང་བ
  volume: ''
  author: ''
