id: I2BFCB9F3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T21:05:40+00:00'
last_modified: '2022-06-08T12:33:28.614951+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W24686
  title: སྒྲུབ་བརྒྱུད་ཀརྨ་ཀཾ་ཚང་གི་བརྒྱུད་པ་རིན་པོ་ཆེའི་རྣམ་པར་ཐར་པ་རབ་འབྱམས་ནོར་བུ་ཟླ་བ་ཆུ་ཤེལ་གྱི་ཕྲེང་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3C6B:
      image_group_id: I1GS105611
      title: ''
      total_pages: 958
      order: 1
      base_file: 3C6B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
